site_name: ripple
site_description: A JAX-based package for differentiable gravitational-wave waveform generation
site_author: GW JAX Team
repo_url: https://github.com/GW-JAX-Team/ripple
repo_name: GW-JAX-Team/ripple

theme:
    name: material
    features:
        - navigation
        - toc
        - header.autohide
    palette:
        - scheme: slate
          primary: black
          accent: amber
          toggle:
             icon: material/brightness-5
             name: Light mode
        - scheme: default
          primary: blue
          accent: deep purple
          toggle:
             icon: material/brightness-2
             name: Dark mode

markdown_extensions:
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.superfences
    - pymdownx.details
    - pymdownx.snippets:
        base_path: docs
    - admonition
    - toc:
        permalink: "¤"
        toc_depth: 4

plugins:
    - search
    - autorefs
    - mkdocs-jupyter:
        include: ["*.ipynb"]
    - gen-files:
        scripts:
        - docs/gen_ref_pages.py
    - literate-nav:
        nav_file: SUMMARY.md
    - mkdocstrings:
        handlers:
            python:
                options:
                    docstring_style: google
                    filters: ["!^logger$"]
                    inherited_members: true
                    show_root_heading: true
                    show_root_full_path: true
                    show_if_no_docstring: true
                    show_signature_annotations: true
                    show_source: false
                    members_order: source
                    heading_level: 3

nav:
    - Home: index.md
    - Installation: installation.md
    - Quick Start: quickstart.md
    - Tutorials:
        - Overview: tutorials/index.md
        - Generating Waveforms: tutorials/generating_waveforms.ipynb
    - FAQ: FAQ.md
    - Contributing: contributing.md
    - API: api/ripplegw/*
